apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-service-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crypto-service
      version: green
  template:
    metadata:
      labels:
        app: crypto-service
        version: green
    spec:
      containers:
        - name: crypto-service
          image: your-registry/crypto-service:green
          ports:
            - containerPort: 80
