name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx for multi-platform support
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub using GitHub secrets for credentials
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 4: Build and push Docker images
    - name: Build and Push Docker Images
      run: |
        services=("crypto_price_service" "transaction_service" "account_service")
        for service in "${services[@]}"; do
          echo "Processing $service..."
          
          # Build Docker image for the service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$service:latest ./src/$service
          
          # Push Docker image to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/$service:latest
        done

    # Step 5: Check Docker version
    - name: Check Docker version
      run: docker --version

    # Step 6: Clean up Docker resources
    - name: Clean up
      run: docker system prune -f
